name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'

      - name: Install deps
        run: |
          pip install flet pillow
          flutter doctor
          flutter precache

      - name: Build APK
        run: |
          flet build apk --verbose
          ls -R build/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/**/*.apk
